name: CI/CD-For-Timify

on:
  push:
    branches:
      - ci/19

jobs:
  my-action:
    runs-on: ubuntu-latest

    steps:
      # 리포지토리 체크아웃
      - name: Checkout
        uses: actions/checkout@v3

      # JDK 17 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      # gradlew 실행 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      # Gradle로 빌드
      - name: Build with Gradle
        run: ./gradlew clean build
        shell: bash

      # 버전 관리를 위한 현재 시간 생성
      - name: Generate current time
        id: current-time
        run: echo "formattedTime=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      # 배포 패키지 생성
      - name: Generate deployment package
        run: |
          mkdir -p deploy
          cp build/libs/*.jar deploy/
          cp Procfile deploy/
          cp -r .ebextensions deploy/
          cp -r .platform deploy/
          cd deploy && zip -r deploy.zip .
        shell: bash

      # Elastic Beanstalk에 배포
      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: timify-springboot-application
          environment_name: Timify-springboot-application-env
          version_label: Github Action-${{ env.formattedTime }}
          region: ap-northeast-2
          deployment_package: deploy/deploy.zip
          wait_for_deployment: false
