name: CI/CD-For-Timify

on:
  push:
    branches:
      - ci/19

jobs:
  my-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Install and update AWS CLI
        run: |
          if command -v aws &> /dev/null; then
            echo "AWS CLI is already installed. Updating..."
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install --update
          else
            echo "Installing AWS CLI..."
            sudo apt-get update
            sudo apt-get install -y unzip curl
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
          fi
          aws --version

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ap-northeast-2

      - name: Get current version
        id: get-version
        run: |
          VERSION_LABEL=$(aws elasticbeanstalk describe-environments --application-name timify-springboot-application --environment-name Timify-springboot-application-env --query "Environments[0].VersionLabel" --output text)
          echo "VERSION_LABEL=${VERSION_LABEL}" >> $GITHUB_ENV
          echo "Current version label: ${VERSION_LABEL}"

      - name: Generate new version label
        id: generate-version-label
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          NEW_VERSION_LABEL=GitHubAction-${COMMIT_HASH}-$(date +'%Y%m%d%H%M%S')
          echo "NEW_VERSION_LABEL=${NEW_VERSION_LABEL}" >> $GITHUB_ENV
          echo "New version label: ${NEW_VERSION_LABEL}"

      - name: Generate deployment package
        run: |
          mkdir -p deploy
          cp build/libs/*.jar deploy/
          cp Procfile deploy/
          cp -r .ebextensions deploy/
          cp -r .platform deploy/
          cd deploy && zip -r deploy.zip .

      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@v16
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: timify-springboot-application
          environment_name: Timify-springboot-application-env
          version_label: ${{ env.NEW_VERSION_LABEL }}
          region: ap-northeast-2
          deployment_package: deploy/deploy.zip
          wait_for_deployment: false

      - name: Wait for environment to be ready
        id: wait-for-ready
        run: |
          ATTEMPTS=0
          MAX_ATTEMPTS=30
          SLEEP_TIME=60
          while [ $ATTEMPTS -lt $MAX_ATTEMPTS ]; do
            ENV_STATUS=$(aws elasticbeanstalk describe-environments --application-name timify-springboot-application --environment-name Timify-springboot-application-env --query "Environments[0].Status" --output text)
            if [ "$ENV_STATUS" == "Ready" ]; then
              echo "Environment is ready for update."
              exit 0
            fi
            echo "Environment status is '$ENV_STATUS'. Waiting for it to be ready..."
            ATTEMPTS=$((ATTEMPTS + 1))
            sleep $SLEEP_TIME
          done
          echo "Environment was not ready after $MAX_ATTEMPTS attempts."
          exit 1

      - name: Update Elastic Beanstalk environment
        run: |
          aws elasticbeanstalk update-environment --application-name timify-springboot-application --environment-name Timify-springboot-application-env --version-label ${{ env.NEW_VERSION_LABEL }}
